### ISSUE TITLE
Syntax error when parsing single apostrophe in element value

### ISSUE THREAD

**Issue by owain68** [kontent-ai/model-generator-js#37] opened 2023-01-14 10:20 UTC
### Brief bug description
Created './content-types/cmp.ts'
Created './content-types/tag.ts'
Created './taxonomies/regulator_categories.ts'
Created './project/languages.ts'
Created './project/collections.ts'
Created './project/contentTypes.ts'
Created './project/contentTypeSnippets.ts'
Created './project/taxonomies.ts'
Created './project/workflows.ts'
Created './project/roles.ts'
Failed with error:
SyntaxError: ',' expected. (69:34)
  67 | alzheimerSSociety: {
  68 |                 id: '8139bc72-1ed7-51d9-b74d-245841a93cf1',
> 69 |                 name: 'Alzheimer's Society',
     |                                  ^
  70 |                 externalId: 'b7c0b5ac-c444-4614-8626-29c06dfcce61',
  71 |                 folders: {}},

### Repro steps

1. Run model generator against a project which contains a text element that contains a single apostrophe

### Expected behavior

Runs to completion and parses the data correctly

### Test environment

 - Platform/OS: macOS Ventura M1
 - "@kontent-ai/model-generator": "^5.9.0" installed using npm

### Screenshots

<img width="565" alt="screenshot_242" src="https://user-images.githubusercontent.com/191453/212467237-28faaeae-cc23-4241-94a2-e8c042da54b6.png">

**Comment by Enngage** [comment] 2023-01-19 12:38
I'll have a look in the upcoming week and release a new version if all goes well.

**Comment by Enngage** [comment] 2023-01-26 07:24
@owain68 I was not able to reproduce this on my side. Can you provide more details?

When using an apostrophe in the `Text` element's name, the generator successfully renders my model. This was generated in `contentTypes.ts`:

```
       /**
       * Test's apostrophe (text)
       */
      test_s_apostrophe: {
        codename: 'test_s_apostrophe',
        id: '81a528aa-7975-4114-8832-4deeb1ccae99',
        externalId: undefined,
        name: "Test's apostrophe",
        required: false,
        type: 'text',
        snippetCodename: undefined,
      }
```

**Comment by Enngage** [comment] 2023-02-07 08:55
I'll close this for now. Feel free to reopen if you encounter this again.

**Comment by owain68** [comment] 2023-02-13 08:23
@Enngage Richard I am still getting this.  I have been running a debugger across it and I can isolate the problem a little more.

<img width="1204" alt="screenshot_274" src="https://user-images.githubusercontent.com/191453/218315920-b7534364-bb36-4e2b-9f81-f1f09a928a87.png">

The problem seems to be in project.generator.ts in the code being generated.
<img width="1099" alt="screenshot_275" src="https://user-images.githubusercontent.com/191453/218316013-8065eb20-1977-4a3d-8ced-7cd81bef5658.png">

You can see the code being generated is not handling the single quote. `name: 'Alzheimer's Society',`
`
/**
* Alzheimer's Society
*/
alzheimerSSociety: {
                id: '8139bc72-1ed7-51d9-b74d-245841a93cf1',
                name: 'Alzheimer's Society',
                externalId: 'b7c0b5ac-c444-4614-8626-29c06dfcce61',
                folders: {}},

/**
* Alzheimer'sResearchUK
*/
alzheimerSResearchUK: {
                id: '5e4c5f22-36b6-5cc6-a10b-d95c46869899',
                name: 'Alzheimer'sResearchUK',
                externalId: 'c3c680b7-18cc-41cc-8dab-c5c45b57ed80',
                folders: {}},
`

**Comment by owain68** [comment] 2023-02-13 12:00
@Enngage I have amended the options as suggested but now get a different error

`import * as dotenv from 'dotenv'
dotenv.config({path: '../.env'})
import { generateModelsAsync } from '@kontent-ai/model-generator';

const { projectId, apiKey } = process.env;
(async () => {
  await generateModelsAsync({
    sdkType: 'delivery',
    projectId,
    isEnterpriseSubscription: false,
    apiKey,
    addTimestamp: true,
    formatOptions: {
      singleQuote: false
    },
    elementResolver: 'camelCase',
    exportRoles: false,
    outputDir: '../generated-output'
  })
  // …
})()`

The error is
`
            triggerUncaughtException(err, true /* fromPromise */);
            ^

SyntaxError: Unexpected token (22:27)
  20 |                 externalId: undefined,
  21 |                 name: 'Default project language'}
> 22 |                 } as const;
     |                           ^
    at f (/Users/owain/dev/kontent-generate-model-in-code-example/node_modules/prettier/parser-babel.js:22:1054)

`
I think you are likely correct that it is a MacOS v Windows line ending type thing.

**Comment by Enngage** [comment] 2023-02-13 12:28
@owain68 yeah, please reach out to support and send them your API Keys and they will generate it for you. I've already asked JanH to assist you ;)

**Comment by Enngage** [comment] 2023-02-20 09:34
Hi @owain68, I've fixed the issue and you should not be able to generate your project successfully :) Please upgrade to `v5.10.0`. 

Hope it helps and sorry for the troubles! It turns out the problem was with missing escape function on the webhook name and the use of '+' character.

**Closed by Enngage** 2023-02-20 09:34 UTC
Labels: bug

**Comment by Enngage** [comment] 2023-02-20 15:23
@owain68 I have actually run the generator on your project that you provided to our support and it worked ok... Maybe this is the part which fails because of the MacOs and line endings?
